package upmsp.algorithm.neighborhood;

import upmsp.model.*;
import upmsp.model.solution.*;

import java.util.*;

/**
 * This class represents a Shift Move (as in the paper). A neighbor in the Shift Move is generated by re-scheduling one
 * job from the machine with the largest total execution time (or a random machine) to another position in the machine.
 * The parameter "useMakespanMachine" determines whether the machine with the largest total execution time is always
 * used.
 *
 * @author Tulio Toffolo
 */
public class TwoShift extends Move {

    private Machine machine;
    private int pos1_1, pos1_2, pos2_1, pos2_2, job1, job2;
    private boolean useMakespanMachine;

    /**
     * Instantiates a new Shift Move.
     *
     * @param problem            problem.
     * @param random             random number generator.
     * @param priority           the priority of this neighborhood.
     * @param useMakespanMachine true if the makespan machine should be always considered or false otherwise.
     */
    public TwoShift(Problem problem, Random random, int priority, boolean useMakespanMachine) {
        super(problem, random, "2-Shift" + (useMakespanMachine ? "(mk)" : ""), priority);
        this.useMakespanMachine = useMakespanMachine;
    }

    public void accept() {
        super.accept();
    }

    public int doMove(Solution solution) {
        super.doMove(solution);

        // selecting machines to involve in operation
        if (useMakespanMachine && solution.makespanMachine.getNJobs() > 1) {
            machine = solution.makespanMachine;
        }
        else {
            int m;
            do {
                m = random.nextInt(solution.machines.length);
            }
            while (solution.machines[m].getNJobs() <= 1);
            machine = solution.machines[m];
        }

        // removing first job
        pos1_1 = random.nextInt(machine.getNJobs());
        job1 = machine.jobs[pos1_1];
        machine.delJob(pos1_1);

        // removing second job
        pos2_1 = random.nextInt(machine.getNJobs());
        job2 = machine.jobs[pos2_1];
        machine.delJob(pos2_1);

        // adding first job
        pos1_2 = random.nextInt(machine.getNJobs() + 1);
        machine.addJob(job1, pos1_2);

        // adding second job
        pos2_2 = random.nextInt(machine.getNJobs() + 1);
        machine.addJob(job2, pos2_2);

        solution.updateCost();
        return deltaCost = solution.getCost() - initialCost;
    }

    public boolean hasMove(Solution solution) {
        return !useMakespanMachine || solution.makespanMachine.getNJobs() > 1;
    }

    public void reject() {
        super.reject();

        machine.delJob(pos2_2);
        machine.delJob(pos1_2);

        machine.addJob(job2, pos2_1);
        machine.addJob(job1, pos1_1);

        currentSolution.updateCost();
    }
}
